import Modal from "@/components/Modal"
import "./globals.css"

export const metadata = {
  title: "Trello Clone ",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#F5F6F8] dark:bg-gray-700">
        {children}
        <Modal />
      </body>
    </html>
  )
}
